// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuKe3DxECbQGX8inYZKnSvJchjicHctEQ',
    appId: '1:96247855006:web:1142fce5d61bf386d1c88f',
    messagingSenderId: '96247855006',
    projectId: 'karokojnr-6396f',
    authDomain: 'karokojnr-6396f.firebaseapp.com',
    storageBucket: 'karokojnr-6396f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqwcxZj7tU4-ir52ngm3pXUC2HEFJ7XrA',
    appId: '1:96247855006:android:b5b287a6eb0be9add1c88f',
    messagingSenderId: '96247855006',
    projectId: 'karokojnr-6396f',
    storageBucket: 'karokojnr-6396f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU3W4u0aLSQQrjOo1zSBV_9uC-gNTNHq8',
    appId: '1:96247855006:ios:f01d4732e398d58bd1c88f',
    messagingSenderId: '96247855006',
    projectId: 'karokojnr-6396f',
    storageBucket: 'karokojnr-6396f.appspot.com',
    iosClientId: '96247855006-76lncmj9s9dh7dodaiea69rsobbaecoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU3W4u0aLSQQrjOo1zSBV_9uC-gNTNHq8',
    appId: '1:96247855006:ios:56fe6aabcad28949d1c88f',
    messagingSenderId: '96247855006',
    projectId: 'karokojnr-6396f',
    storageBucket: 'karokojnr-6396f.appspot.com',
    iosClientId: '96247855006-i89c4glc8bc5a8rliqngfeueimnn2uli.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
